import{FetchGraphQL as g}from"./fetch-graphql.js";const n={failedFetch:"Failed to fetch config from backend with status:",failedSetStorageConfig:"Failed to set storage config",failedGetStorageConfig:"Configuration could not be loaded.",failedExecutionRecaptcha:"Recaptcha execution failed",failedInitializing:"An error occurred while initializing ReCaptcha:"},l={PLACE_ORDER:"placeOrder",CONTACT:"contactUs",CUSTOMER_LOGIN:"generateCustomerToken",CUSTOMER_FORGOT_PASSWORD:"requestPasswordResetEmail",CUSTOMER_CREATE:"createCustomerV2",CUSTOMER_EDIT:"updateCustomerV2",NEWSLETTER:"subscribeEmailToNewsletter",PRODUCT_REVIEW:"createProductReview",SENDFRIEND:"SENDFRIEND",BRAINTREE:"BRAINTREE"},d=".grecaptcha-badge iframe",u=(a,e)=>{if(a&&a.forms){const t=a.forms.concat(e).map(r=>typeof r!="string"?{...r,enabledBadgePlace:!1}:{badgeId:l[r],enabledBadgePlace:!1});return{...a,forms:[...new Set(t)]}}return{}},h=async(a,e=1,t=1e3)=>{const r=sessionStorage.getItem(a);return r!==null?JSON.parse(r):e>0?(await new Promise(o=>setTimeout(o,t)),h(a,e-1,t)):null},f=(a,e,t)=>{if(!a||!e.website_key)return null;try{sessionStorage.setItem(a,JSON.stringify(e))}catch(r){return t&&console.error(n.failedSetStorageConfig,r),null}},p=a=>new Promise(e=>{if(document.querySelector(a)){e(!0);return}const t=new MutationObserver(()=>{document.querySelector(a)&&(e(!0),t.disconnect())});t.observe(document.body,{childList:!0,subtree:!0})}),_=async()=>await p(d),{failedExecutionRecaptcha:s}=n,m=async a=>{if(!window.grecaptcha)return Promise.reject(s);try{return await window.grecaptcha.execute(a,{action:"click"})}catch(e){return Promise.reject(`${s} : ${e}`)}},C=()=>new Promise(a=>{const e=new MutationObserver((r,o)=>{window.grecaptcha&&(o.disconnect(),a(!0))}),t={childList:!0,subtree:!0,attributes:!0};e.observe(document.body,t)}),b=async(a,e,t)=>(window.grecaptcha||await C(),grecaptcha.ready(()=>{const r=document.querySelectorAll(`#${a}`);r.length&&(r.forEach(o=>o.id=`${o.id}_${Math.random().toString(36)}`),r.forEach(o=>{if(o.innerHTML==="")try{grecaptcha.render(o.id,{sitekey:e.website_key,badge:e.badge_position,size:"invisible",theme:e.theme||"light"})}catch(i){t&&console.error(i)}}))})),w=`query {
  recaptchaV3Config {
    is_enabled
    website_key
    minimum_score
    badge_position
    language_code
    failure_message
    forms
    theme
  } 
}`,c=new g().getMethods();class y{constructor(){var e;this._enableReCAPTCHA=!1,this._recaptchaBackendEndpoint=((e=c.getConfig())==null?void 0:e.endpoint)||"",this._recaptchaScriptUrl="https://www.google.com/recaptcha/api.js",this._configStorageKey="recaptchaConfig",this._logger=!1}async _updateBadgePosition(e,t){if(t){if((t==null?void 0:t.badge_position)!=="inline"){if(!await _())return;const o=document.querySelector(d);t.theme&&o&&(!o.src.includes("theme=dark")||!o.src.includes("theme=light"))&&o.setAttribute("src",`${o.src}&theme=${t.theme}`);return}await b(e,t,this._logger)}}async _addRecaptchaScript(){const e=await this._loadConfig();if(!document.getElementById("recaptchaId")&&e){const t=e.website_key,r=e.badge_position==="inline",o=e.language_code;if(!t)return;const i=document.createElement("script");i.setAttribute("id","recaptchaId"),i.defer=!0,i.src=r?`${this._recaptchaScriptUrl}?render=${t}&badge=none&hl=${o}`:`${this._recaptchaScriptUrl}?render=${t}&badge=${e.badge_position}&hl=${o}`,document.head.appendChild(i)}}async _fetchStoreConfig(){var e;try{const t=await c.fetchGraphQl(w,{method:"GET",cache:"force-cache"});if((e=t==null?void 0:t.errors)!=null&&e.length){this._logger&&console.error(t.errors[0].message);return}return t}catch(t){this._logger&&console.error(`${n.failedFetch}:`,t)}}async _loadConfig(){const e=await h(this._configStorageKey);return e?(this._enableReCAPTCHA=!!e.is_enabled,e):(this._logger&&console.error(n.failedGetStorageConfig),null)}setEndpoint(e){e&&(this._recaptchaBackendEndpoint=e,c.setEndpoint(e))}async setConfig(e){var t;try{const r=await this._fetchStoreConfig();if(!((t=r==null?void 0:r.data)!=null&&t.recaptchaV3Config)){sessionStorage.removeItem(this._configStorageKey);return}const o=u(r.data.recaptchaV3Config,e);f(this._configStorageKey,o,this._logger)}catch(r){this._logger&&console.error(n.failedSetStorageConfig,r),sessionStorage.removeItem(this._configStorageKey)}}async initReCaptcha(e=3e3){setTimeout(()=>{(async()=>{try{const t=await this._loadConfig();if(!(t!=null&&t.forms)||!t.is_enabled)return;await this._addRecaptchaScript();for(const r of t.forms)await this._updateBadgePosition(r.badgeId,t)}catch(t){this._logger&&console.error(n.failedInitializing,t)}})()},e)}async verifyReCaptcha(){try{const e=await this._loadConfig();return!(e!=null&&e.forms)||!e.website_key||!e.is_enabled?void 0:await m(e.website_key)}catch(e){this._logger&&console.error(e)}}enableLogger(e){this._logger=e}getMethods(){return{enableLogger:this.enableLogger.bind(this),setEndpoint:this.setEndpoint.bind(this),setConfig:this.setConfig.bind(this),initReCaptcha:this.initReCaptcha.bind(this),verifyReCaptcha:this.verifyReCaptcha.bind(this)}}}const S=new y,{initReCaptcha:E,verifyReCaptcha:T,setEndpoint:I,setConfig:A,enableLogger:O}=S.getMethods();export{y as RecaptchaModule,O as enableLogger,E as initReCaptcha,c as recaptchaFetchApi,A as setConfig,I as setEndpoint,T as verifyReCaptcha};
